server:
  port: 8081
  servlet:    context-path: /mfs-auth
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauthdb?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:format_sql: true